### ISSUE TITLE
Model for Business Operations List panel

### ISSUE THREAD

**Issue by zelcion** [mapikit/meta-editor#51]

**Comment by lukineas** [comment]
Something like this?

![Image](https://github.com/user-attachments/assets/ffaac020-4df4-4416-978a-0018d6a60e61)

(inspired by the [Schema Overview Design](https://github.com/mapikit/meta-editor/issues/10))
the BOp overview allows to see, create and edit the existing BOps in your system
- each card (when opened) displays useful data about its contents
- it also has a description for context
- like the schema, BOps added by addons can be identified by the icon in front of its name

maybe i'm missing the mark so tell me if this is the way to go
I commented on this before but i think we should use the cog icon to enter the BOps config, instead of the pencil, to avoid confusion
